name: DAST - OWASP ZAP Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    name: Build and Run .NET App
    runs-on: ubuntu-latest
    outputs:
      app-url: ${{ steps.start-app.outputs.app-url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x' # Altere conforme sua versão

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Start API (background)
        id: start-app
        run: |
          dotnet run --no-build --urls "http://localhost:5109" &
          echo "app-url=http://localhost:8000" >> $GITHUB_OUTPUT
        shell: bash

      - name: Wait for the API to start (health check)
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8000/; then
              echo "API is up!"
              exit 0
            fi
            echo "Waiting for API..."
            sleep 2
          done
          echo "API did not start in time"
          exit 1

  zap-scan:
    name: ZAP DAST Scan
    runs-on: ubuntu-latest
    needs: build-and-run
    steps:
      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:5109'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: 'Relatório de Vulnerabilidades DAST da ExpertIA'
          fail_action: true
